FORMAT: 1A
HOST: http://www.google.com

# Login
JSON contracts between back and front end for login functionality

# Group LoginValidate

Login first step with nickname input

Form parameters:
<ul>
    <li>username</li>
    <li>password</li>
    <li>rememberMe</li>
</ul>
    
_eventId:
<ul>
    <li>Submit: validateUser</li>
    <li>Forgot username: rememberUser</li>
</ul>

## Username validation [/pages/login/validate.json]
### Valid [GET]
+ Response 200 (application/json)

        {
            "alerts": null
        }

## Username validation with errors [/pages/login/validate.json?mockId=2]
### Error [GET]
+ Response 200 (application/json)

        {
            "alerts": [
                {
                    "type": "ERROR",
                    "alert": [
                        {
                            "text": "Error message 1",
                            "field": ""
                        }
                    ]
                }
            ]
        }
        
## Remembered user [/pages/login/validate.json?mockId=3]
### Password [GET]
+ Response 200 (application/json)

        {
            "alerts": null,
            "pageContent": {
                "remembered": true,
                "nickname": "Marcos Manuel",
                "username": "marcosmon",
                "lastSignonDate": "Wednesday 03/12/2014"
            }
        }

## Remembered user systemOutage [/pages/login/validate.json?mockId=rememberSystemOutage]
### Password [GET]
+ Response 200 (application/json)

        {
            "alerts": [
                {
                    "type": "WARN",
                    "alert": [
                        {
                            "text": "System unavailable. Please try again later."
                        }
                    ]
                }
            ],
            "pageContent": {
                "remembered": true,
                "nickname": "Marcos Manuel",
                "username": "marcosmon",
                "lastSignonDate": "Wednesday 03/12/2014",
                "systemOutage": true
            }
        }
        
## SystemOutage [/pages/login/validate.json?mockId=systemOutage]
### Password [GET]
+ Response 200 (application/json)

        {
           "alerts": [
                {
                    "type": "WARN",
                    "alert": [
                        {
                            "text": "System unavailable. Please try again later."
                        }
                    ]
                }
            ],
            "pageContent": {
                "systemOutage": true
            }
        }
        
# Group LoginChallenge

Login second step (optional, just if device is not recognized) with security answer input

Form parameters:
<ul>
    <li>securityAnswer</li>
    <li>rememberDevice</li>
</ul>
    
_eventId: validateQuestion

## First access [/pages/login/challenge.json]
### Challenge [GET]
+ Response 200 (application/json)

        {
            "alerts": null,
            "pageContent": {
                "securityQuestion": "What was the name of your first pet?"
            }
        }

## Security answer error [/pages/login/challenge.json?mockId=2]
### Challenge [GET]
+ Response 200 (application/json)

        {
            "alerts": [
                {
                    "type": "ERROR",
                    "alert": [
                        {
                            "text": "Wrong answer. Verify it and try again.",
                            "field": ""
                        }
                    ]
                }
            ],
            "pageContent": {
                "securityQuestion": "What was the name of your first pet?"
            }
        }

# Group LoginTermsAndConditions

Login last step (optional, if user didn't accept the lastest T&C) with Terms and Conditions acceptance.

Form parameters:
<ul>
    <li>validateTerms</li>
    <li>declineTerms</li>
</ul>
    
_eventId: validateTerms

## Access [/pages/login/termsAndConditions.json]
### Terms and conditions [GET]
+ Response 200 (application/json)

        {
            "alerts": null,
            "pageContent" : {
                "iframeUrl": "http://www.bbvacompass.com/mobile-banking/v4/terms?requestAcceptance=1&platform=web",
                "mail": {
                    "body": "The most recent version of the BBVA Compass Mobile Banking Terms of Use is available at the web address below. To keep a record of the current version, please print or save a copy when you receive this email.",
                    "subject": "BBVA Compass Mobile Banking Terms of Use",
                    "urlTermsMail": "http://www.bbvacompass.com/mobile-banking/v4/terms"
                }
            }
        }

# Group LoginECATerms

Login last step (optional, if user didn't accept the lastest T&C) with ECA Terms acceptance.

Form parameters:
<ul>
    <li>validateTerms</li>
    <li>declineTerms</li>
</ul>
    
_eventId: validateTerms

## Access [/pages/login/ECATerms.json]
### Terms and conditions [GET]
+ Response 200 (application/json)

        {
            "alerts": null,
            "pageContent" : {
                "iframeUrl": "https://www.bbvacompass.com/mobile-banking/v4/ECATerms/?requestAcceptance=1&platform=web",
                "ecaTerms": true,
                "mail": {
                    "body": "The most recent version of the Electronic Communications Agreement is available at the web address below. To keep a record of the current version, please print or save a copy when you receive this email.",
                    "urlTermsMail": "https://www.bbvacompass.com/mobile-banking/v4/ECATerms/"
                }
            }
        }

# Group Nickname Account

User's nickname recovery first step

Form parameters:
<ul>
    <li>accountNumber</li>
    <li>email</li>
</ul>
    
_eventId: validateAccount

## First access [/pages/login/nicknameAccount.json]
### Challenge [GET]
+ Response 200 (application/json)

        {
            "alerts": null,
            "pageContent": {
            }
        }

# Group Recovery Challenge

User's nickname recovery second step

Form parameters:
<ul>
    <li>securityAnswer</li>
</ul>
    
_eventId: validateQuestion

## First access [/api/login/recoveryChallenge.json]
### Challenge [GET]
+ Response 200 (application/json)

        {} && {
            "status": "OK",
            "pageContent": {
            },
            "flowExecutionUrl": "/index.html?e2s2"
        }

## Wrong answer [/pages/login/recoveryChallenge.json?mockId=2]
### Wrong answer [GET]
+ Response 200 (application/json)

        {
            "header": {
                "title": "Forgot username"
            },
            "alerts": [
                {
                    "type": "ERROR",
                    "alert": [
                        {
                            "text": "Wrong answer. Verify it and try again.",
                            "field": ""
                        }
                    ]
                }
            ],
            "pageContent": {
                "securityQuestion": "What was the name of your first pet?"
            }
        }

# Group Password Account

User's password recovery first step

Form parameters:
<ul>
    <li>accountNumber</li>
</ul>
    
_eventId: validateAccount

## First access [/pages/login/passwordAccount.json]
### Challenge [GET]
+ Response 200 (application/json)

        {
            "alerts": null,
            "pageContent": {
            }
        }


# Group Change Password

Change the user's password

Form parameters:
<ul>
   <li>currentPassword</li>
   <li>newPassword</li>
   <li>confirmPassword</li>
</ul>

    
_eventId: confirmsChangePassword

## First access [/pages/login/changePassword.json]
### Challenge [GET]
+ Response 200 (application/json)

        {
            "alerts": null,
            "pageContent": {
            }
        }

# Group Enrollment

Shows the enrollment form

Form parameters:
<ul>
   <li>accountNumber</li>
   <li>pin</li>
   <li>username</li>
   <li>password</li>
   <li>passwordConfirm</li>
   <li>email</li>
   <li>emailConfirm</li>
</ul>

    
_eventId: activateUser

## Correct answer [/pages/login/enrollment.json]
### Activate [GET]
+ Response 200 (application/json)

        {
            "alerts": null, 
            "pageContent": [
                {
                    "accountSubType": "ATM",
                    "label": "ATM/Check Card",
                    "minLength": "16",
                    "maxLength": "16"
                }, {
                    "accountSubType": "CHK",
                    "label": "Checkings, Savings or Money Market",
                    "minLength": "8",
                    "maxLength": "10"
                }, {
                    "accountSubType": "CRC",
                    "label": "Credit Card or Line of Credit (with card)",
                    "minLength": "15",
                    "maxLength": "16"
                }, {
                    "accountSubType": "CRCWC",
                    "label": "Line of Credit (without card)",
                    "minLength": "15",
                    "maxLength": "16"
                }, {
                    "accountSubType": "LOA",
                    "label": "Loan or Mortgage",
                    "minLength": "7",
                    "maxLength": "10"
                }, {
                    "accountSubType": "CDA",
                    "label": "CD",
                    "minLength": "5",
                    "maxLength": "10"
                }, {
                    "accountSubType": "IRB",
                    "label": "IRA",
                    "minLength": "5",
                    "maxLength": "10"
                }    
            ],
            "flowExecutionUrl": "/api/login/validateAccount.json?eventId=validateAccount"
        }

# Group validateAccount

Validate Account for enrollment

Form parameters:
<ul>
   <li>accountNumber</li>
   <li>pin</li>
   <li>cvv</li>
   <li>ssnumber</li>
   <li>dateBirth</li>
   <li>zipCode</li>
</ul>
    
_eventId: activateUser

## Correct answer [/api/login/validateAccount.json]
### Activate [GET]
+ Response 200 (application/json)

        {} && {
            "alerts": null,
            "status": "OK",
            "flowExecutionUrl": "/api/login/activateUser.json?eventId=activateUser",
            "pageContent": null
        }

# Group User activation

Activate the user for enrollment

Form parameters:
<ul>
   <li>username</li>
   <li>password</li>
   <li>passwordConfirm</li>
   <li>email</li>
   <li>emailConfirm</li>
</ul>
    
_eventId: enroll

## Correct answer [/api/login/activateUser.json]
### Activate [GET]
+ Response 200 (application/json)

        {} && {

            "status": "OK",
            "flowExecutionUrl": "/api/login/activateUser.json?mockId=3&_eventId=enroll",
            "pageContent": {
                "challengeQuestions":[
                   {
                      "questionId":"Q1.14",
                      "questionText":"What was the name of your junior high school?"
                   },
                   {
                      "questionId":"Q1.17",
                      "questionText":"What was your first car?"
                   },
                   {
                      "questionId":"Q1.24",
                      "questionText":"What town did you meet your spouse in for the first time?"
                   },
                   {
                      "questionId":"Q1.21",
                      "questionText":"What town did your maternal grandmother live in?"
                   },
                   {
                      "questionId":"Q1.22",
                      "questionText":"What is the middle name of your best friend?"
                   },
                   {
                      "questionId":"Q1.19",
                      "questionText":"What was the name of your elementary school?"
                   },
                   {
                      "questionId":"Q1.16",
                      "questionText":"What was the first name of your first manager?"
                   },
                   {
                      "questionId":"Q1.15",
                      "questionText":"What was the name of the first company you worked for?"
                   },
                   {
                      "questionId":"Q1.20",
                      "questionText":"What was your childhood nickname?"
                   },
                   {
                      "questionId":"Q1.18",
                      "questionText":"What was the year and make of your first car?"
                   },
                   {
                      "questionId":"Q1.13",
                      "questionText":"What was the name of your first pet?"
                   },
                   {
                      "questionId":"Q1.23",
                      "questionText":"What is the first name of your first college roommate?"
                   }
                ]
            }
        }

## Wrong pin [/api/login/activateUser.json?mockId=2]
### Error [GET]
+ Response 200 (application/json)

        {} && {
            "alerts": [
                {
                    "type": "ERROR",
                    "alert": [
                        {
                            "text": "Wrong Pin",
                            "field": "pin"
                        }
                    ]
                }
            ],
            "flowExecutionUrl": "/api/login/activateUser.json?execution=1",
            "status": "ERROR",
            "pageContent": null
        }

## Enroll ok [/api/login/activateUser.json?mockId=3]
### Error [GET]
+ Response 200 (application/json)

        {} && {
            "alerts": [
                {
                    "type": "OK",
                    "alert": [
                        {
                            "text": "Enroll Ok"
                        }
                    ]
                }
            ],
            "status": "OK",
            "flowExecutionUrl": "/accounts.html?execution=1",
            "pageContent": null
        }

# Group UncompleteEnrollment

Shows the uncompleteEnrollment form

Form parameters:
<ul>
   <li>questionId (list)</li>
   <li>answerText (list)</li>
</ul>
    
## Correct answer [/pages/login/uncompleteEnrollment.json]
### Activate [GET]
+ Response 200 (application/json)

        {
            "alerts": null, 
            "pageContent": {
                "challengeQuestions":[
                   {
                      "questionId":"Q1.14",
                      "questionText":"What was the name of your junior high school?"
                   },
                   {
                      "questionId":"Q1.17",
                      "questionText":"What was your first car?"
                   },
                   {
                      "questionId":"Q1.24",
                      "questionText":"What town did you meet your spouse in for the first time?"
                   },
                   {
                      "questionId":"Q1.21",
                      "questionText":"What town did your maternal grandmother live in?"
                   },
                   {
                      "questionId":"Q1.22",
                      "questionText":"What is the middle name of your best friend?"
                   },
                   {
                      "questionId":"Q1.19",
                      "questionText":"What was the name of your elementary school?"
                   },
                   {
                      "questionId":"Q1.16",
                      "questionText":"What was the first name of your first manager?"
                   },
                   {
                      "questionId":"Q1.15",
                      "questionText":"What was the name of the first company you worked for?"
                   },
                   {
                      "questionId":"Q1.20",
                      "questionText":"What was your childhood nickname?"
                   },
                   {
                      "questionId":"Q1.18",
                      "questionText":"What was the year and make of your first car?"
                   },
                   {
                      "questionId":"Q1.13",
                      "questionText":"What was the name of your first pet?"
                   },
                   {
                      "questionId":"Q1.23",
                      "questionText":"What is the first name of your first college roommate?"
                   }
                ]
            },
            "flowExecutionUrl": "/api/login/activateUser.json?mockId=3&_eventId=enroll"
        }

        
# Group Enroll user

Enrolls the user in online banking

Form parameters:
<ul>
   <li>username</li>
   <li>password</li>
   <li>passwordConfirm</li>
   <li>email</li>
   <li>emailConfirm</li>
   <li>questionId (list)</li>
   <li>answerText (list)</li>

</ul>

_eventId: signIn

## Correct answer [/api/login/enroll.json]
### Enroll [GET]
+ Response 200 (application/json)

        {} && {
            "header": {
                "title": "Terms of Use"
            },
            "alerts": null,
            "status": "OK",
            "flowExecutionUrl": "/login/termsAndConditions.html?execution=1",
            "pageContent": null
        }
        
# Group Activate credit card

Activate credit card

Form parameters:
<ul>
   <li>accountNumber</li>
   <li>cvv</li>
   <li>ssnumber</li>
</ul>

_eventId: signIn

## Activate credit card [/pages/login/activateCreditCard.json]

### List All Questions [GET]

+ Response 200 (application/json)

        {
            "alerts": "",
            "status": "OK",
            "pageContent": {
                "hasErrorPDF": true
            },
            "flowExecutionUrl": "/api/accounts/checkPDF.json?execution=e1s1"
        }
        
# Group Recovery Nickname

User's nickname recovery first step

Form parameters:
<ul>
    <li>email</li>
    <li>accountNumber</li>
</ul>
    
_eventId: validateAccount

## First access [/pages/login/recoveryNickname.json]
### Challenge [GET]
+ Response 200 (application/json)

        {
            "alerts": null,
            "pageContent": {
            },
            "flowExecutionUrl": "/api/login/validateQuestion.json?mockId=2"
        }
        
# Group Recovery Password

User's nickname recovery first step

Form parameters:
<ul>
    <li>username</li>
</ul>
    
_eventId: validateUsername

## First access [/pages/login/recoveryPassword.json]
### Challenge [GET]
+ Response 200 (application/json)

        {
            "alerts": null,
            "pageContent": "pablotest",
            "flowExecutionUrl": "/api/login/recoveryPasswordUsername.json?mockId=2"
        }


## Second access [/api/login/recoveryPasswordUsername.json]
### Challenge [GET]
+ Response 200 (application/json)

        {} && {
            "status": "OK",
            "pageContent": {
            },
            "flowExecutionUrl": "/api/login/validateQuestion.json?mockId=2"
        }

## Third access [/api/login/validateQuestion.json]
### Challenge [GET]
+ Response 200 (application/json)

        {} && {
            "status": "OK",
            "pageContent": {
                "securityQuestion": "What was the name of your first pet?"
            },
            "flowExecutionUrl": "/api/login/recoveryChallenge.json?mockId=2"
        }

# Group Reenrollment

Shows the reenrollment form

Form parameters:
<ul>
   <li>password</li>
</ul>
    
_eventId: requestReset

## Forgot answer [/pages/login/passmarkReset.json]
### Activate [GET]
+ Response 200 (application/json)

        {
            "alerts": null,
            "header": {
                "title": "Forgot Answer"
            },
            "pageContent": "forgot",
            "flowExecutionUrl": "/api/login/requestReset.json?eventId=requestReset"
        }
        
## Unlock user [/pages/login/passmarkReset.json?mockId=unlock]
### Activate [GET]
+ Response 200 (application/json)

        {
            "alerts": null,
            "header": {
                "title": "Unlock"
            },
            "pageContent": "unlock",
            "flowExecutionUrl": "/api/login/requestReset.json?eventId=requestReset"
        }

# Group Validate Password

Validate Password for reenrollment

Form parameters:
<ul>
   <li>password</li>
</ul>
    
_eventId: requestReset

## Correct answer [/api/login/requestReset.json]
### Activate [GET]
+ Response 200 (application/json)

        {} && {
            "alerts": null,
            "status": "OK",
            "flowExecutionUrl": "/api/login/securityCode.json?eventId=securityCode",
            "pageContent": null
        }

# Group Security Code
        
Validate Security Code for reenrollment

Form parameters:
<ul>
   <li>securityCode</li>
</ul>
    
_eventId: verifySecurityCode

## Correct answer [/api/login/securityCode.json]
### Activate [GET]
+ Response 200 (application/json)

        {} && {
            "alerts": null,
            "status": "OK",
            "flowExecutionUrl": "/api/login/reenroll.json?eventId=reenroll",
            "pageContent": {
                "challengeQuestions":[
                   {
                      "questionId":"Q1.14",
                      "questionText":"What was the name of your junior high school?"
                   },
                   {
                      "questionId":"Q1.17",
                      "questionText":"What was your first car?"
                   },
                   {
                      "questionId":"Q1.24",
                      "questionText":"What town did you meet your spouse in for the first time?"
                   },
                   {
                      "questionId":"Q1.21",
                      "questionText":"What town did your maternal grandmother live in?"
                   },
                   {
                      "questionId":"Q1.22",
                      "questionText":"What is the middle name of your best friend?"
                   },
                   {
                      "questionId":"Q1.19",
                      "questionText":"What was the name of your elementary school?"
                   },
                   {
                      "questionId":"Q1.16",
                      "questionText":"What was the first name of your first manager?"
                   },
                   {
                      "questionId":"Q1.15",
                      "questionText":"What was the name of the first company you worked for?"
                   },
                   {
                      "questionId":"Q1.20",
                      "questionText":"What was your childhood nickname?"
                   },
                   {
                      "questionId":"Q1.18",
                      "questionText":"What was the year and make of your first car?"
                   },
                   {
                      "questionId":"Q1.13",
                      "questionText":"What was the name of your first pet?"
                   },
                   {
                      "questionId":"Q1.23",
                      "questionText":"What is the first name of your first college roommate?"
                   }
                ]
            }
        }
    
# Group Reenroll user

Reenrolls the user in online banking

Form parameters:
<ul>
   <li>password</li>
   <li>securityCode</li>
   <li>questionId (list)</li>
   <li>answerText (list)</li>

</ul>

_eventId: signIn

## Correct answer [/api/login/reenroll.json]
### Enroll [GET]
+ Response 200 (application/json)

        {} && {
            "alerts": [
                {
                    "type": "OK",
                    "alert": [
                        {
                            "text": "Your access to Mobile Banking has been successfully unlocked."
                        }
                    ]
                }
            ],
            "status": "OK",
            "flowExecutionUrl": "/accounts.html?execution=1",
            "pageContent": null
        }
